version: '3.8'
services:
  mysql:
    image: mysql
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: emartdbpass
      MYSQL_DATABASE: book
    volumes:
      msqldat: /var/lib/mysql
    networks:
      - connection
  
  mongodb:
    image: mongo
    container_name: emongo
    environment:
      MONGO_INITDB_DATABASE: epoc
    volumes:
      mogoda: /data/db
    networks:
      - connection
    ports:
      - "2000:2000"
  nginx:
    build:
      context: ./nginx
    networks:
      - connection
    ports:
      - "80:80"
    depends_on:
  

  clientapp:
    build: 
      context: ./client
    container_name: client
    networks:
      - connection
    ports:
      - "4200:4200"
    depends_on:
      - javaapi
      - nodeapi

  javaapi:
    build:
      context: ./javaapi
    container_name: javaapi
    ports:
      - "5000:5000"
    restart: always
    networks:
      - connection
    depends_on:
      - mysql
  
  nodeapi:
    build: 
      context: ./nodeapi
    container_name: nodeapi
    ports:
      - "9000:9000"
    restart: always
    networks:
      - connection
    depends_on:
      - mongodb
networks:
  connection:
volumes:
  msqldat:
  mogoda: